apiVersion: v1
kind: ConfigMap
metadata:
  name: example-cm
data:
  database_name: mongodb
  log_level: warn
  custom_data: |
     I am a test line
     min_size=2GB
     max_thread=100
     hello=world
